[workspace]
members = [
  "rust/1-hello-world",
  "rust/2-reverse-string",
  "rust/3-gigasecond",
  "rust/beer-song",
  "rust/4-clock",
  "rust/5-anagram",
  "rust/7-sublist",
  "rust/assembly-line",
  "rust/armstrong-numbers",
  "rust/difference-of-squares",
  "rust/grains",
  "rust/health-statistics",
  "rust/high-scores",
  "rust/low-power-embedded-game",
  "rust/lucians-luscious-lasagna",
  "rust/magazine-cutout",
  "rust/resistor-color",
  "rust/role-playing-game",
  "rust/rpn-calculator",
  "rust/semi-structured-logs",
  "rust/short-fibonacci",
]

resolver = "2"
