[workspace]
members = [
  "rust/anagram",
  "rust/armstrong-numbers",
  "rust/assembly-line",
  "rust/beer-song",
  "rust/clock",
  "rust/difference-of-squares",
  "rust/gigasecond",
  "rust/grains",
  "rust/health-statistics",
  "rust/hello-world",
  "rust/high-scores",
  "rust/leap",
  "rust/low-power-embedded-game",
  "rust/lucians-luscious-lasagna",
  "rust/magazine-cutout",
  "rust/resistor-color",
  "rust/reverse-string",
  "rust/role-playing-game",
  "rust/rpn-calculator",
  "rust/semi-structured-logs",
  "rust/short-fibonacci",
  "rust/sublist",
]

resolver = "2"
