[workspace]
members = [
  "rust/01-hello-world",
  "rust/02-reverse-string",
  "rust/03-gigasecond",
  "rust/04-clock",
  "rust/05-anagram",
  "rust/07-sublist",
  "rust/10-armstrong-numbers",
  "rust/11-beer-song",
  "rust/12-difference-of-squares",
  "rust/13-grains",
  "rust/14-leap",
  "rust/21-high-scores",
  "rust/assembly-line",
  "rust/health-statistics",
  "rust/low-power-embedded-game",
  "rust/lucians-luscious-lasagna",
  "rust/magazine-cutout",
  "rust/resistor-color",
  "rust/role-playing-game",
  "rust/rpn-calculator",
  "rust/semi-structured-logs",
  "rust/short-fibonacci",
]

resolver = "2"
