name: Pull Request
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths: [
      "**/*.jsonc",
      "**/*.json",
      "**/*.yml",
      "**/*.md",
      "bash/**/*.bats",
      "bash/**/*.bash",
      "Cargo.toml",
      "rust/**/*.rs",
      "rust/**/*.toml",
    ]
  push:
    branches: [main]
    paths: [
      "**/*.jsonc",
      "**/*.json",
      "**/*.yml",
      "**/*.md",
      "bash/**/*.bats",
      "bash/**/*.bash",
      "Cargo.toml",
      "rust/**/*.rs",
      "rust/**/*.toml",
    ]

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      bash_any_changed: ${{ steps.changed-files.outputs.bash_any_changed }}
      rs_any_changed: ${{ steps.changed-files.outputs.rs_any_changed}}
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v44
        id: changed-files
        with:
          files_yaml: |
            bash:
              - bash/**/*.bash
              - bash/**/*.bats
            rs:
              - rust/**/*.rs
              - rust/**/*.toml

  test:
    needs: changed-files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - if: needs.changed-files.outputs.rs_any_changed == 'true'
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - if: needs.changed-files.outputs.rs_any_changed == 'true'
        uses: Swatinem/rust-cache@v2.7.3
      - if: needs.changed-files.outputs.rs_any_changed == 'true'
        name: Run Cargo tests
        run: just _tests-rust-ci
      - if: needs.changed-files.outputs.bash_any_changed == 'true'
        name: Install bats
        run: sudo apt install bats
      - if: needs.changed-files.outputs.bash_any_changed == 'true'
        name: Run Bats tests
        run: just tab

  style:
    needs: changed-files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - if: needs.changed-files.outputs.rs_any_changed == 'true'
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt,clippy
      - if: needs.changed-files.outputs.rs_any_changed == 'true'
        uses: Swatinem/rust-cache@v2.7.3

      - if: needs.changed-files.outputs.bash_any_changed == 'true'
        uses: mfinelli/setup-shfmt@v3
      - uses: extractions/setup-just@v2

      - uses: dprint/check@v2.2
        name: Check files format

      - if: needs.changed-files.outputs.rs_any_changed == 'true'
        name: Lint Rust files
        run: just lr
      - if: steps.files-changed.outputs.bash_any_changed == 'true'
        name: Lint Bash files
        run: just lb
