name: Pull Request
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2

      - name: Get changed files
        id: files-changed
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
            rs:
              - rust/**/*.rs
              - .github/workflows/test.yml
            bash:
              - bash/**/*.bats
              - .github/workflows/test.yml

      - if: steps.files-changed.outputs.rs_any_changed == 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Run Cargo tests
        if: steps.files-changed.outputs.rs_any_changed == 'true'
        run: just tar

      - name: Install bats
        if: steps.files-changed.outputs.bash_any_changed == 'true'
        run: sudo apt install bats

      - name: Run Bats tests
        if: steps.files-changed.outputs.bash_any_changed == 'true'
        run: just tab

  style:
    name: style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2

      - name: Get changed files
        id: files-changed
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
            rs:
              - rust/**/*.rs
              - .github/workflows/test.yml
            bash:
              - bash/**/*.bats
              - .github/workflows/test.yml

      - if: steps.files-changed.outputs.rs_any_changed == 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Format and Lint Rust files
        if: steps.files-changed.outputs.rs_any_changed == 'true'
        run: just fcr lr

      - name: Format and Lint Bash files
        if: steps.files-changed.outputs.bash_any_changed == 'true'
        run: just fcb lb
