name: Test
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: files-changed
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
            rs:
              - rust/**/*.rs
              - .github/workflows/test.yml
            bash:
              - bash/**/*.bats
              - .github/workflows/test.yml

      - name: Install Rust toolchain
        if: steps.files-changed.outputs.rs_any_changed == 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Run Cargo tests
        if: steps.files-changed.outputs.rs_any_changed == 'true'
        run: cargo test --all

      - name: Install bats
        if: steps.files-changed.outputs.bash_any_changed == 'true'
        run: sudo apt install bats

      - name: Run Bats tests
        if: steps.files-changed.outputs.bash_any_changed == 'true'
        run: find bash -mindepth 1 -maxdepth 1 -type d -exec bash -c 'cd "{}" && bats -r .' \;
