name: Test
on:
  pull_request:
    branches: [main]
    paths: ['rust/**/*.{rs,toml}']
  push:
    branches: [main]
    paths: ['rust/**/*.{rs,toml}']
jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-02-18
          profile: minimal
          override: true

      - name: Install nextest
        run: cargo install cargo-nextest --locked

      - name: Run tests
        run: cargo nextest run --all --cargo-quiet
