name: Test
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths: ['rust/**/*.{rs,toml}']
  push:
    branches: [main]
    paths: ['rust/**/*.{rs,toml}']
jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1

      - name: Run tests
        run: cargo test --all
